services:
  # ---------------------
  # Zookeeper
  # ---------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  # ---------------------
  # Kafka Broker
  # ---------------------
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  # ---------------------
  # Source Container
  # ---------------------
  source:
    build: ./stages/source
    depends_on:
      - kafka
    develop:
      watch:
        - path: ./stages/source
          action: sync
          target: /app/

  # ---------------------
  # Enhance (Flink) Container
  # ---------------------
  enhance:
    build: ./stages/enhance
    depends_on:
      - kafka
    develop:
      watch:
        - path: ./stages/enhance
          action: sync
          target: /app/

  # ---------------------
  # Sink Container
  # ---------------------
  sink:
    build: ./stages/sink
    depends_on:
      - kafka
    develop:
      watch:
        - path: ./stages/sink
          action: sync
          target: /app/
